---

- name: Install bluetooth tools
  ansible.builtin.package:
    name:
      - blueman
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Enable Bluetooth service
  ansible.builtin.service:
    name: bluetooth
    state: started
    enabled: true
