---

- name: Install bluetooth tools
  package:
    name:
      - blueman
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Enable Bluetooth service
  service: 
    name: bluetooth
    state: started
    enabled: yes
