---
# Sample rate configs
PA_SAMPLE_FORMAT: float32le
PA_SAMPLE_RATE: 48000
PA_ALT_SAMPLE_RATE: 44100
PA_SAMPLE_CHANNEL: 2
PA_RESAMPLE_METHOD: soxr-vhq

# Channel mapping
PA_DEFAULT_CHANNEL_MAP: front-left,front-right
PA_DEFAULT_FRAGMENTS: 2
PA_DEFAULT_FRAGMENT_SIZE: 125
PA_ENABLE_LFE_MIXING: false

# Scheduling configuration for pulse daemon
PA_HIGH_PRIORITY: true
PA_NICENESS: -11
PA_REALTIME_SCHEDULING: true
PA_REALTIME_PRIORITY: 9
PA_RLIMIT_RTPRIO: 9
PA_DAEMONIZE: false
