mirrors:
  - http://pkg.adfinis.com/archlinux/$repo/os/$arch
  - https://pkg.adfinis.com/archlinux/$repo/os/$arch
  - http://mirror.init7.net/archlinux/$repo/os/$arch
  - https://mirror.init7.net/archlinux/$repo/os/$arch
  - http://mirror.puzzle.ch/archlinux/$repo/os/$arch
  - https://mirror.puzzle.ch/archlinux/$repo/os/$arch
  - https://theswissbay.ch/archlinux/$repo/os/$arch
  - https://mirror.ungleich.ch/mirror/packages/archlinux/$repo/os/$arch
